/* =========================================================
   MENU CONFIG
========================================================= */
const MENU=[
 {label:'Dashboard', icon:'grid', page:'mainDashboard'},
 {label:'Supplier & Pembelian', icon:'cart', page:'supplierDashboard', children:[
   {header:'Master & Setting'},
   {label:'Supplier', page:'masterSupplier'},
   {label:'Supplier Group', page:'supplierGroup'},
   {label:'Jurnal Pembelian', page:'jurnalPembelian'},
   {label:'Jurnal A.P.', page:'placeholder', title:'Jurnal A.P.'},
   {label:'Jurnal Biaya Impor', page:'placeholder', title:'Jurnal Biaya Impor'},
   {label:'Estimasi Hari Pengiriman', page:'placeholder', title:'Estimasi Hari Pengiriman'},
   {header:'Daftar Transaksi'},
   {label:'Tutup Pending PO', page:'placeholder', title:'Tutup Pending PO'},
   {label:'Uang Muka Supplier', page:'placeholder', title:'Uang Muka Supplier'},
   {label:'Transaksi A.P.', page:'placeholder', title:'Transaksi A.P.'},
   {label:'Permintaan Pembelian', page:'placeholder', title:'Permintaan Pembelian'},
   {label:'Tutup PR', page:'placeholder', title:'Tutup PR'},
   {label:'Purchase Order', page:'purchaseOrder'},
   {label:'Terima Barang', page:'terimaBarang'},
   {label:'Retur PB', page:'placeholder', title:'Retur PB'},
   {label:'Pembelian Melalui BPB', page:'pembelianBPB'},
   {label:'Pembelian dari PO', page:'placeholder', title:'Pembelian dari PO'},
   {label:'Pembelian Langsung', page:'placeholder', title:'Pembelian Langsung'},
   {label:'Biaya Impor V.1', page:'placeholder', title:'Biaya Impor V.1'},
   {label:'Pelunasan Utang', page:'pelunasanUtang'},
   {label:'Retur Pembelian', page:'placeholder', title:'Retur Pembelian'},
   {label:'Pengajuan Pembayaran', page:'placeholder', title:'Pengajuan Pembayaran'},
   {header:'Transaksi Konsinyasi'},
   {label:'Inventory Target Restock Cabang', page:'placeholder', title:'Inventory Target Restock Cabang'},
   {label:'Delivery Request (Cabang)', page:'placeholder', title:'Delivery Request (Cabang)'},
   {label:'Delivery Request (HO)', page:'placeholder', title:'Delivery Request (HO)'},
   {label:'Terima Barang DR', page:'placeholder', title:'Terima Barang DR'},
   {label:'Po Konsinyasi', page:'placeholder', title:'Po Konsinyasi'},
   {label:'Pembelian Konsinyasi', page:'placeholder', title:'Pembelian Konsinyasi'},
 ]},
 {label:'Customer & Penjualan', icon:'invoice', page:'salesDashboard', children:[
   {header:'Master & Setting'},
   {label:'Lead', page:'placeholder', title:'Lead'},
   {label:'Customer', page:'customers'},
   {label:'History Credit Limit', page:'placeholder', title:'History Credit Limit'},
   {label:'Grup Customer', page:'customerGroup'},
   {label:'Tipe Customer', page:'placeholder', title:'Tipe Customer'},
   {label:'Master Syarat Customer Grup', page:'placeholder', title:'Master Syarat Customer Grup'},
   {label:'Jurnal Penjualan', page:'jurnalPenjualan'},
   {label:'Jurnal A.R.', page:'placeholder', title:'Jurnal A.R.'},
   {label:'Promotion', page:'promotion'},
   {label:'Dominasi', page:'dominasi'},
   {label:'Salesman', page:'salesman'},
   {label:'Sales Office', page:'salesOffice'},
   {label:'Weekday', page:'placeholder', title:'Weekday'},
   {label:'Rumus Komisi Salesman', page:'placeholder', title:'Rumus Komisi Salesman'},
   {label:'Komisi Per Item', page:'placeholder', title:'Komisi Per Item'},
   {label:'Badan Usaha', page:'placeholder', title:'Badan Usaha'},
   {label:'Alasan Retur', page:'placeholder', title:'Alasan Retur'},
   {header:'Daftar Transaksi'},
   {label:'Tutup Pending SO', page:'placeholder', title:'Tutup Pending SO'},
   {label:'Uang Muka Customer', page:'placeholder', title:'Uang Muka Customer'},
   {label:'Transaksi A.R.', page:'placeholder', title:'Transaksi A.R.'},
   {label:'Transaksi A.R. SSP', page:'penerimaanSsp'},
   {label:'Surat Pesanan Ekatalog & Khusus', page:'placeholder', title:'Surat Pesanan Ekatalog & Khusus'},
   {label:'Sales Quotation', page:'salesQuotation'},
   {label:'Tutup Sales Quotation', page:'placeholder', title:'Tutup Sales Quotation'},
   {label:'Tracking Status', page:'placeholder', title:'Tracking Status'},
   {label:'Sales Order', page:'salesOrders'},
   {label:'Picking List', page:'pickingList'},
   {label:'Invoice', page:'invoices'},
   {label:'Packing', page:'packing'},
   {label:'Update Document Status Surat Jalan', page:'placeholder', title:'Update Document Status Surat Jalan'},
   {label:'Retur Surat Jalan', page:'placeholder', title:'Retur Surat Jalan'},
   {label:'Penjualan Via S.J.', page:'fakturPenjualanSJ'},
   {label:'Penjualan Langsung', page:'placeholder', title:'Penjualan Langsung'},
   {label:'Penerimaan Piutang', page:'penerimaanPiutang'},
   {label:'Retur Penjualan', page:'placeholder', title:'Retur Penjualan'},
   {label:'Document Status Retur Penjualan', page:'placeholder', title:'Document Status Retur Penjualan'},
   {label:'Consignment Refund', page:'placeholder', title:'Consignment Refund'},
   {label:'T3F', page:'placeholder', title:'T3F'},
   {label:'Daftar Tagih Piutang', page:'placeholder', title:'Daftar Tagih Piutang'},
 ]},
 {label:'Persediaan Barang', icon:'box', page:'inventoryDashboard', children:[
   {header:'Master & Setting'},
   {label:'Inventory', page:'items'},
   {label:'Gudang', page:'gudang'},
   {label:'Zat Kandungan Aktif', page:'zatKandunganAktif'},
   {label:'Farmakoterapi', page:'farmakoterapi'},
   {label:'Sub-Farmakoterapi', page:'subFarmakoterapi'},
   {label:'Bentuk Sediaan', page:'bentukSediaan'},
   {label:'Kategori Barang', page:'kategoriBarang'},
   {label:'Group Produk', page:'groupProduk'},
   {label:'Daftar Kategory Reordering Sheet', page:'kategoriReorderingSheet'},
   {label:'Rack', page:'placeholder', title:'Rack'},
   {label:'Jurnal Persediaan', page:'placeholder', title:'Jurnal Persediaan'},
   {label:'Duplikat Barang', page:'placeholder', title:'Duplikat Barang'},
   {label:'Berat Produk', page:'placeholder', title:'Berat Produk'},
   {label:'Area Limit Sales', page:'placeholder', title:'Area Limit Sales'},
   {label:'Price List By Province', page:'priceListProvince'},
   {label:'HS Code', page:'placeholder', title:'HS Code'},
   {label:'Satuan', page:'placeholder', title:'Satuan'},
   {header:'Daftar Transaksi'},
   {label:'Reordering Sheet', page:'reorderingSheet'},
   {label:'Stock Request', page:'stockRequest'},
   {label:'Transaksi Persediaan', page:'transaksiPersediaan'},
   {label:'Master Stock Opname', page:'placeholder', title:'Master Stock Opname'},
   {label:'Stock Opname', page:'placeholder', title:'Stock Opname'},
   {label:'Adjust Harga Jual', page:'placeholder', title:'Adjust Harga Jual'},
   {label:'Klaim Bonus Item', page:'placeholder', title:'Klaim Bonus Item'},
   {label:'Terima Klaim Bonus Item', page:'placeholder', title:'Terima Klaim Bonus Item'},
 ]},
 {label:'Kas/Bank', icon:'wallet', page:'kasbankDashboard', children:[
   {header:'Master & Setting'},
   {label:'Master Bank', page:'placeholder', title:'Master Bank'},
   {label:'Kas/Bank', page:'kasBank'},
   {label:'Currency', page:'placeholder', title:'Currency'},
   {label:'Jurnal Pelunasan Utang/Piutang', page:'placeholder', title:'Jurnal Pelunasan Utang/Piutang'},
   {label:'Jurnal Kas Lain-Lain', page:'placeholder', title:'Jurnal Kas Lain-Lain'},
   {label:'Cash Flow', page:'placeholder', title:'Cash Flow'},
   {header:'Daftar Transaksi'},
   {label:'Transaksi Kas', page:'transaksiKas'},
   {label:'Daftar Giro Mundur', page:'placeholder', title:'Daftar Giro Mundur'},
   {label:'Rekonsiliasi', page:'placeholder', title:'Rekonsiliasi'},
 ]},
 {label:'General Ledger', icon:'book', page:'glDashboard', children:[
   {header:'Master & Setting'},
   {label:'Akun GL', page:'akunGL'},
   {label:'GL Kategori', page:'glKategori'},
   {label:'Cabang', page:'cabang'},
   {label:'Cost Center', page:'costCenter'},
   {label:'Budgeting', page:'placeholder', title:'Budgeting'},
   {label:'Budgeting Cc.', page:'placeholder', title:'Budgeting Cc.'},
   {label:'Rumus Rasio Keuangan', page:'placeholder', title:'Rumus Rasio Keuangan'},
   {label:'G.L. Template', page:'placeholder', title:'G.L. Template'},
   {header:'Daftar Transaksi'},
   {label:'Transaksi G.L.', page:'jurnalUmum'},
 ]},
 {label:'Aktiva Tetap', icon:'truck', children:[
   {header:'Master & Setting'},
   {label:'Fixed Asset', page:'aktivaTetap'},
   {label:'Lokasi', page:'lokasiAset'},
   {label:'Jurnal Aktiva Tetap', page:'jurnalFixedAsset'},
   {label:'Rumus Penyusutan', page:'aktivaTetapDeprRule'},
   {header:'Daftar Transaksi'},
   {label:'Pembelian Aktiva Tetap', page:'placeholder', title:'Pembelian Aktiva Tetap'},
   {label:'Penjualan Aktiva Tetap', page:'placeholder', title:'Penjualan Aktiva Tetap'},
   {label:'Biaya Asset', page:'placeholder', title:'Biaya Asset'},
   {label:'Disposal Asset', page:'placeholder', title:'Disposal Asset'},
   {label:'Revaluasi Asset', page:'placeholder', title:'Revaluasi Asset'},
 ]},
 {label:'Lain-lain', icon:'list', children:[
   {label:'Wilayah', page:'masterWilayah'},
   {label:'Auto Number 2', page:'placeholder', title:'Auto Number 2'},
   {label:'Auto Number Tax', page:'placeholder', title:'Auto Number Tax'},
   {label:'Business Centre', page:'businessCentre'},
   {label:'Rayon', page:'masterRayon'},
   {label:'Remarks', page:'placeholder', title:'Remarks'},
   {label:'Driver', page:'placeholder', title:'Driver'},
   {label:'Kernet', page:'placeholder', title:'Kernet'},
   {label:'Status AR Customer', page:'placeholder', title:'Status AR Customer'},
   {label:'Syarat Bayar', page:'placeholder', title:'Syarat Bayar'},
   {label:'Daftar PPh', page:'placeholder', title:'Daftar PPh'},
   {label:'Daftar Ppn', page:'placeholder', title:'Daftar Ppn'},
   {label:'Remote Printer', page:'placeholder', title:'Remote Printer'},
   {label:'Master Custom Field', page:'placeholder', title:'Master Custom Field'},
   {label:'Coretax Export', page:'placeholder', title:'Coretax Export'},
   {label:'Kode Transaksi Pajak', page:'placeholder', title:'Kode Transaksi Pajak'},
   {label:'Kode Tipe Pajak', page:'placeholder', title:'Kode Tipe Pajak'},
   {label:'Kode Cabang Pajak', page:'placeholder', title:'Kode Cabang Pajak'},
   {label:'Ekspedisi', page:'placeholder', title:'Ekspedisi'},
   {label:'Harga Ekspedisi', page:'placeholder', title:'Harga Ekspedisi'},
   {label:'Order Via', page:'placeholder', title:'Order Via'},
   {label:'Email Template', page:'placeholder', title:'Email Template'},
   {label:'Master Divisi', page:'divisi'},
   {label:'Picker & Packer', page:'placeholder', title:'Picker & Packer'},
   {label:'Master Template', page:'placeholder', title:'Master Template'},
   {label:'Alasan Belum Tertagih', page:'placeholder', title:'Alasan Belum Tertagih'},
   {label:'Documentation Open API', page:'placeholder', title:'Documentation Open API'},
 ]},
 {label:'Pengaturan', icon:'settings', children:[
   {label:'Update Software', page:'placeholder', title:'Update Software'},
   {label:'Backup & Restore', page:'placeholder', title:'Backup & Restore'},
   {label:'Tutup Buku', page:'placeholder', title:'Tutup Buku'},
   {label:'Schedule Maintenance', page:'placeholder', title:'Schedule Maintenance'},
   {label:'Generasi Sementara', page:'placeholder', title:'Generasi Sementara'},
   {label:'Data Transfer', page:'placeholder', title:'Data Transfer'},
   {label:'Saldo Awal', page:'placeholder', title:'Saldo Awal'},
   {label:'Administrasi Bulanan', page:'adminBulanan'},
   {label:'Regenerate Journal', page:'placeholder', title:'Regenerate Journal'},
   {label:'Import Transaction', page:'placeholder', title:'Import Transaction'},
   {label:'Import Custom Field', page:'placeholder', title:'Import Custom Field'},
   {label:'Export Master', page:'placeholder', title:'Export Master'},
 ]},
 {label:'User Security', icon:'shield', children:[
   {label:'Master User', page:'users'},
   {label:'Group User', page:'groupUser'},
   {label:'Hak Akses Group', page:'placeholder', title:'Hak Akses Group'},
   {label:'Hak Akses Group Report', page:'placeholder', title:'Hak Akses Group Report'},
   {label:'Activity Log', page:'placeholder', title:'Activity Log'},
   {label:'Hak Approval', page:'placeholder', title:'Hak Approval'},
   {label:'User Aktif', page:'placeholder', title:'User Aktif'},
   {label:'Error Logs', page:'placeholder', title:'Error Logs'},
 ]},
 {label:'Daftar Laporan', icon:'chart', children:[
   {label:'Cetakan Transaksi', page:'reportCetakanTransaksi'},
   {label:'Account Receivable', page:'reportAR'},
   {label:'Penjualan', page:'reportPenjualan'},
   {label:'Account Payable', page:'reportAP'},
   {label:'Purchasing', page:'reportPurchasing'},
   {label:'Persediaan Barang', page:'reportPersediaan'},
   {label:'Kas/Bank', page:'reportKasBank'},
   {label:'General Ledger', page:'reportGL'},
   {label:'Aktiva Tetap', page:'reportAktivaTetap'},
   {label:'Cabang', page:'reportCabang'},
   {label:'Laporan Kustom', page:'placeholder', title:'Laporan Kustom'},
   {label:'Chart / Grafik', page:'placeholder', title:'Chart / Grafik'},
   {label:'Dashboard', page:'placeholder', title:'Dashboard Laporan'},
 ]},
 {label:'Profil Perusahaan', icon:'folder', page:'companyProfile'},
];

